Repository retepasw/joomla-italiapa, pull requests merged in 2021-01, with the labels that each got.

#374 Content - Vote for ItaliaPA - jcfields warning
  plugins/content/ipavote/ipavote.php
Labels: RTC, bug

#375 Articoli in evidenza di tutte le categorie (layout: Hero news) - Carousel
  templates/italiapa/html/com_content/featured/heronews.php
Labels: enhancement

#376 Articoli in evidenza di tutte le categorie - Carousel
  templates/italiapa/html/com_content/featured/default.php
Labels: enhancement

#378 Plugin System ItaliaPA - Undefined index notice
  plugins/system/italiapa/italiapa.php
Labels: bug

#377 Articoli - Categoria blog - Carousel
  templates/italiapa/html/com_content/category/blog.php
Labels: enhancement

#385 Corretta referenza esterna articolo
  templates/italiapa/html/layouts/joomla/content/info_block/xreference.php
Labels: RTC, bug

#386 Corrette icone doppie nei contatti
  templates/italiapa/css/italiapa.css
  templates/italiapa/css/italiapa.min.css
  templates/italiapa/html/com_contact/category/default_links.php
  templates/italiapa/html/com_contact/category/organigramma_links.php
  templates/italiapa/html/com_contact/contact/default_links.php
Labels: RTC

#387 Ottimizzazione fogli di stile
  templates/italiapa/css/ita.css
  templates/italiapa/css/italiapa.min.css
  templates/italiapa/index.php
  templates/italiapa/script.php
Labels: RTC

#388 SimpleXMLElement::addAttribute(): Attribute already exists
  plugins/system/italiapa/src/joomla/joomla/form/fields/checkbox.php
Labels: RTC, bug

#389 Notice: Undefined offset: 0
  plugins/system/italiapa/src/joomla/src/Form/Form.php
Labels: RTC, bug

#393 Modulo Articoli Correlati - layout dropdown - Notice: Undefined property: stdClass::$link
  templates/italiapa/html/layouts/eshiol/module/dropdown.php
  templates/italiapa/html/mod_related_items/dropdown.php
Labels: RTC, bug

#397 Dl shift+enter
  media/plg_system_ipatinymce/css/content.css
  media/plg_system_ipatinymce/css/content.min.css
  media/plg_system_ipatinymce/js/plugin.js
  media/plg_system_ipatinymce/js/plugin.min.js
Labels: RTC, enhancement
