Repository retepasw/joomla-italiapa, pull requests merged in 2021-02, with the labels that each got.

#398 Update templateDetails.xml
  templates/italiapa/templateDetails.xml
Labels: bug

#404 Megamenu - ripristinato comportamento it web toolkit
  templates/italiapa/html/mod_menu/megamenu.php
Labels: RTC

#406 Articoli - Categoria blog - layout Masonry
  templates/italiapa/build/build.css
  templates/italiapa/build/build.min.css
  templates/italiapa/html/com_content/category/masonry.php
Labels: RTC, bug

#409 Articoli - Categoria blog layout Masonry - formattazione titolo
  templates/italiapa/html/com_content/category/masonry_item.php
Labels: RTC, bug

#408 Sito in manutenzione
  templates/italiapa/build/build.css
  templates/italiapa/build/build.italia.css
  templates/italiapa/build/build.italia.min.css
  templates/italiapa/build/build.italiaaa.css
  templates/italiapa/build/build.italiaaa.min.css
  templates/italiapa/build/build.min.css
  templates/italiapa/build/build.scuola.css
  templates/italiapa/build/build.scuola.min.css
  templates/italiapa/build/build.squola.css
  templates/italiapa/build/build.squola.min.css
  templates/italiapa/offline.php
Labels: RTC, new feature

#405 Corretti fogli di stile per tutti i temi disponibili
  templates/italiapa/build/build.css
  templates/italiapa/build/build.italiapa.css
  templates/italiapa/build/build.italiapa.min.css
  templates/italiapa/build/build.min.css
  templates/italiapa/index.php
  templates/italiapa/js/italiapa.js
  templates/italiapa/js/italiapa.min.js
Labels: RTC, bug

#410 Articoli - Categoria blog layout Focus - formattazione titolo
  templates/italiapa/html/com_content/category/focus_simple.php
Labels: RTC, bug

#413 Megamenu - multicolonna - corretta dimensione colonne
  templates/italiapa/css/italiapa.css
  templates/italiapa/css/italiapa.min.css
Labels: RTC, bug

#415 Contatti - Icona telefono
  templates/italiapa/html/com_contact/category/default_links.php
  templates/italiapa/html/com_contact/category/organigramma_links.php
  templates/italiapa/html/com_contact/contact/default_links.php
Labels: RTC, bug

#416 Corretta visualizzazione tooltip
  templates/italiapa/css/italiapa.css
  templates/italiapa/css/italiapa.min.css
  templates/italiapa/css/tooltip-theme-arrows.min.css
Labels: RTC, bug
